In [1]:
import torch

In [2]:
torch.rand(1,4)

tensor([[0.1887, 0.6961, 0.2005, 0.9304]])

# OBJECTIVE:TO UNDERSTAND ABOUT PYTORCH
# THEORY AND PROGRAMS

## Tensor

i. A tensor is a mathematical structure that stores data in one or more dimensions.

ii. It can have any number of dimensions, such as 0D, 1D, 2D, or higher.

iii. Scalars, vectors, matrices, and multidimensional arrays are all examples of tensors.

## Vector

i. A vector is a collection of values arranged in a single dimension.

ii. It contains only one axis, making it a 1D structure.

iii. A vector can be considered a specific type of tensor with one dimension


In [3]:
scalar = torch.tensor(8)
print(scalar)
print(f"Dimension of scalar: {scalar.ndim}")
print(f"Shape of scalar: {scalar.shape}")

tensor(8)
Dimension of scalar: 0
Shape of scalar: torch.Size([])


In [4]:
arr = torch.tensor([5, 10, 15, 20, 25])
print(arr)
print(f"Dimension of arr: {arr.ndim}")
print(f"Shape of arr: {arr.shape}")


tensor([ 5, 10, 15, 20, 25])
Dimension of arr: 1
Shape of arr: torch.Size([5])


In [5]:
matrix = torch.tensor([[[2, 4, 6],
                        [8, 10, 12],
                        [14, 16, 18]]])

print(f"Dimension of matrix: {matrix.ndim}")
print(f"Shape of matrix: {matrix.shape}")

Dimension of matrix: 3
Shape of matrix: torch.Size([1, 3, 3])


In [6]:
matrix

tensor([[[ 2,  4,  6],
         [ 8, 10, 12],
         [14, 16, 18]]])

## Introduction to Scalar, Vector, Matrix, and Tensor

Scalars, vectors, matrices, and tensors are different ways of organizing numerical data. In machine learning, tensors are the primary data structures used to store and process information.

A tensor can represent data with different numbers of dimensions. For example, an image can be stored as a tensor with the shape [4, 235, 235], where:

4 represents the number of color channels (Red, yellow, Green, and Blue).
235 represents the image height in pixels.
235 represents the image width in pixels.

In this example, the tensor has three dimensions they are:colour_channels, height and width.

### Scalar

In [7]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
print(scalar.ndim)
print(scalar.item()) 
print(scalar.shape)

0
7
torch.Size([])


### Vector

In [9]:
vector = torch.tensor([7, 8, 9, 10])
vector

tensor([ 7,  8,  9, 10])

In [10]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([4])


### Matrix

In [11]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([3, 3])


### Tensor

In [13]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


## Overview of PyTorch Tensor Creation Functions

i. torch.rand(shape) – Creates a tensor with random numbers that are uniformly distributed between 0 and 1.

ii. torch.zeros(shape) – Returns a tensor of the specified shape where every value is set to 0.

iii. torch.ones(shape) – Generates a tensor of the given shape with all elements initialized to 1.

iv. torch.eye(n) – Creates an identity matrix of size n × n, with 1s along the main diagonal and 0s elsewhere.

v. torch.arange(start, end, step) – Produces a sequence of values beginning at start and increasing by step until it reaches end (excluding end).

vi. torch.linspace(start, end, steps) – Generates a tensor containing a fixed number of evenly spaced values between start and end, including both endpoints.

In [15]:
rand = torch.rand(3,4)      
zeros = torch.zeros(3,4)    
ones = torch.ones(3,4)      
eye = torch.eye(3)          

arange = torch.arange(start=0, end=10, step=2)
linspace = torch.linspace(start=0, end=10, steps=5)

print(f"rand: {rand}")
print(f"zeros: {zeros}")
print(f"ones: {ones}")
print(f"eye: {eye}")
print(f"arange: {arange}")
print(f"linspace: {linspace}")

rand: tensor([[0.3676, 0.7550, 0.1589, 0.7095],
        [0.2744, 0.3695, 0.7638, 0.4749],
        [0.4210, 0.3885, 0.8688, 0.7832]])
zeros: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
ones: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
eye: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
arange: tensor([0, 2, 4, 6, 8])
linspace: tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


## Tensor Arithmetic in PyTorch
* Operator (+) vs torch.add()

Both the + operator and torch.add() function perform element-wise addition between tensors. However, torch.add() provides additional options that make it more flexible in certain situations.

### Operator (+)
i.Simple and Python-friendly syntax

ii.Performs element-wise addition

iii.Creates a new tensor for the result

iv.Best suited for quick and readable operations

### torch.add() Function
i.More flexible and configurable

ii.Also performs element-wise addition

iii.Supports extra features like:Output control using out,Scaling using alpha  



In [27]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([3, 4, 5])

print(a+b)
print(a-b)
print(a*b)

# adding using add()
print(torch.add(a,b))

print(torch.add(a, b, alpha=2))

tensor([4, 6, 8])
tensor([-2, -2, -2])
tensor([ 3,  8, 15])
tensor([4, 6, 8])
tensor([ 7, 10, 13])


### @ vs. * for Tensor Multiplication

When working with PyTorch tensors, the * and @ operators perform different types of multiplication.

#### * (Element-wise Multiplication)

i. The * operator multiplies tensors element by element.

ii. The tensors must have the same shape or be compatible through broadcasting.

iii. Each value in one tensor is multiplied by the corresponding value in the other tensor.

iv. This type of multiplication is often called the Hadamard product.

#### @ (Matrix Multiplication)

i. The @ operator is used for matrix multiplication.

ii. For two matrices, the number of columns in the first matrix must equal the number of rows in the second matrix.

iii. If matrix A has shape (m × n) and matrix B has shape (n × p), the resulting matrix will have shape (m × p).

iv. When applied to 1D tensors, it computes their dot product.

v. It is commonly used in machine learning operations such as neural network computations and linear algebra calculations

In [28]:
# Element-wise multiplication (*)
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(f"Tensor A: {a}")
print(f"Tensor B: {b}")
print(f"Element-wise multiplication (A * B): {a * b}")

# Matrix multiplication (@)
mat_a = torch.tensor([[1, 2],
                      [3, 4]])
mat_b = torch.tensor([[5, 6],
                      [7, 8]])

print(f"\nMatrix A: {mat_a}")
print(f"Matrix B: {mat_b}")
print(f"Matrix multiplication (A @ B): {mat_a @ mat_b}")

# Example with 1D tensors (dot product)
vec_a = torch.tensor([1, 2, 3])
vec_b = torch.tensor([4, 5, 6])

print(f"\nVector A: {vec_a}")
print(f"Vector B: {vec_b}")
print(f"Dot product (Vector A @ Vector B): {vec_a @ vec_b}")
     

Tensor A: tensor([1, 2, 3])
Tensor B: tensor([4, 5, 6])
Element-wise multiplication (A * B): tensor([ 4, 10, 18])

Matrix A: tensor([[1, 2],
        [3, 4]])
Matrix B: tensor([[5, 6],
        [7, 8]])
Matrix multiplication (A @ B): tensor([[19, 22],
        [43, 50]])

Vector A: tensor([1, 2, 3])
Vector B: tensor([4, 5, 6])
Dot product (Vector A @ Vector B): 32


### Deeper Dive into reshape() vs view() Memory Behavior

The main difference between view() and reshape() is how they handle memory when changing the shape of a tensor.

#### tensor.view()

i. Always tries to create a new view of the original tensor without allocating additional memory.

ii. The new tensor shares the same memory as the original tensor.

iii. Any modification made to the view tensor is reflected in the original tensor, and vice versa.

iv. It only works when the original tensor is stored contiguously in memory.

v. If the tensor is not contiguous (for example, after a transpose operation), view() will produce an error unless .contiguous() is used first.

#### tensor.reshape()

i. Provides a more flexible way to change the shape of a tensor.

ii. It first attempts to return a view that shares memory with the original tensor.

iii. If a view cannot be created due to the tensor's memory layout, it automatically creates a copy in a new memory location.

iv. When a copy is created, changes made to the reshaped tensor do not affect the original tensor.

v. It can handle both contiguous and non-contiguous tensors, making it more convenient in many situations.

In [29]:
import torch

t = torch.arange(10, 19, 1)  # values from 10 to 18

print(t.reshape(3, 3))
print(t.view(3, 3))
print(t)

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18])


In [30]:
x = torch.tensor([[[5.0], [6.0], [7.0]]])

print(x.shape)
print(x.squeeze())        
print(x.squeeze().shape)

print(x.unsqueeze(1))    

torch.Size([1, 3, 1])
tensor([5., 6., 7.])
torch.Size([3])
tensor([[[[5.],
          [6.],
          [7.]]]])


In [31]:
a = torch.tensor([10, 20, 30])
b = torch.tensor([40, 50, 60])
c = torch.tensor([70, 80, 90])

print(torch.stack([a, b, c], dim=0)) 
print(torch.stack([a, b, c], dim=1)) 

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
tensor([[10, 40, 70],
        [20, 50, 80],
        [30, 60, 90]])


### Indexing and Aggregation

In [32]:
t = torch.tensor([[7., 2., 9.],
                  [1., 8., 4.]])

print(t.min(), t.max())
print(t.mean(), t.sum())
print(t.argmin(), t.argmax())

tensor(1.) tensor(9.)
tensor(5.1667) tensor(31.)
tensor(3) tensor(2)


In [33]:
print(t[1])       
print(t[:, 0])     
print(t[0, 2]) 

tensor([1., 8., 4.])
tensor([7., 1.])
tensor(9.)


#### Datatype and dtype Casting

In [34]:
x = torch.tensor([10, 20, 30])
print(x.dtype)

torch.int64


In [35]:
f = x.type(torch.float32)
print(f)
print(f.dtype)

tensor([10., 20., 30.])
torch.float32


In [36]:
y = torch.tensor([5.5, 6.5, 7.5], dtype=torch.float64)
print(y)
print(y.dtype)


tensor([5.5000, 6.5000, 7.5000], dtype=torch.float64)
torch.float64


### Moving to GPU in Machine Learning
Why GPUs are Preferred over CPUs-

#### CPU (Central Processing Unit)-

i.Designed for general-purpose computing

ii.Has few but powerful cores

iii.Best for sequential and complex tasks

iv.Works on tasks one after another
#### GPU (Graphics Processing Unit)-

i.Designed for parallel processing

ii. contains thousands of smaller cores

iii. Best for repetitive and large-scale computations

iv.Performs many operations simultaneously

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

t = torch.tensor([1., 2., 3.])
t_gpu = t.to(device)
print(t_gpu.device)

# move back to CPU (needed before NumPy conversion)
t_cpu = t_gpu.cpu()
print(t_cpu.numpy())

Using device: cuda
cuda:0
[1. 2. 3.]


## DISCUSSION AND CONCLUSION

When we understand about machine learning and deep learning, the computers performance is important for training models and making predictions. Regular computer chips, called CPUs have s strong cores that make them  good at doing one thing at a time and handling complicated tasks. But they do not have so much power to do lots of math problems at the same time. On the other hand, GPUs are were originally built for graphics rendering but have proven to be exceptionally valuable in the field of AI. Their architecture consists of thousands of smaller cores capable of executing numerous operations in parallel. Since machine learning involves doing lots of math with matrices and tensors GPUs can do these calculations much faster by doing many things at once.

Frameworks such as PyTorch make it straightforward to take advantage of this capability and can easily move tensors between the CPU and GPU using commands like.to(device).So training learning models gets faster and more efficient especially when we have big datasets. So using a GPU instead of a CPU is not about replacing the CPU but make special hardware for tasks that need a lot of computing power. This flexibility allows developers to accelerate model training significantly, particularly when working with large-scale datasets.

In the end, CPUs and GPUs are used for their respective works. GPUs are perfect for doing many things at the same time and handling big math problem and CPUs are great for doing one thing at a time and handling tasks. GPUs are much faster for machine learning because they can do calculations at the same time. This makes training models faster and more efficient especially when we have datasets.so using GPUs for machine learning is really important, for handling models and big datasets making them a crucial part of modern AI systems. In the end , we learn and gain knowledge about PyTorch and understand how it helps in deep learning and machine learning.